spring:
  cloud:
    gateway:
      routes:
        - id: product-catalog
          uri: lb://PRODUCT-CATALOG:8081
          predicates:
            - Path=/product/**
        - id: shopping-cart
          uri: lb://shopping-cart:8082
          predicates:
            - Path=/cart/**
            
eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
